import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ReduxProvider from "@/lib/provider";
import Container from "@/components/Layouts/Container";
import Card from "@/components/Layouts/Card";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        <ReduxProvider>
          <Container>
            <Card>{children}</Card>
          </Container>
          {modal}
        </ReduxProvider>
      </body>
    </html>
  );
}
